osx_instance:
  image: mojave-xcode

build_task:
  script: |
    brew install qt5
    brew link qt5 --force
    qmake
    make
release_task:
  name: release
  script: |
    brew install qt5
    brew link qt5 --force
    qmake -config release
    make
    macdeployqt olam.app -dmg
  build_artifacts:
    path: 'olam.dmg'
    type: 'application/x-apple-diskimage'
