osx_instance:
  image: mojave-xcode

build_task:
  script: |
    brew install qt5
    brew link qt5 --force
    qmake
    make

test_task:
  script: |
    brew install qt5
    brew link qt5 --force
    qmake  "CONFIG +=test"
    make
    make check

release_task:
  only_if: $CIRRUS_BRANCH == 'master'
  name: release
  script: |
    brew install qt5
    brew link qt5 --force
    qmake -config release
    make
    macdeployqt build/release/olam.app -dmg
  build_artifacts:
    path: 'olam.dmg'
    type: 'application/x-apple-diskimage'
