image: Visual Studio 2022
version: v1.2.{build}
build:
  verbosity: minimal
install:
  - set QTDIR=C:\Qt\6.9.3\mingw_64
  - set MINGW_BIN=C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\bin
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;%MINGW_BIN%;%PATH%;"C:\Program Files (x86)\Inno Setup 6"
  - copy "%QTDIR%\libstdc++-6.dll" %QTDIR%\bin\
  - copy "%QTDIR%\libgcc*" %QTDIR%\bin\
build_script:
  - qmake olam.pro
  - mingw32-make
after_build:
  - windeployqt --compiler-runtime --release build/release/olam.exe
  - cp -r src/db build/release
  - cp -r src/misc build/release
  - cp LICENSE release
  - iscc olam.iss
artifacts:
  - path: build/release
    type: zip
  - path: Output\olam-*.exe
  
deploy:
  provider: GitHub
  draft: true
  auth_token:
    secure: WObGXwAtWwPh+QNp7LcD/YIKjIS81gvSYUni5bDiXRhu9/YaYDcs2Bxzy5MEUPDZ
  prerelease: false
  on:
    branch: master
