name: olam  # the name of the snap
version: git  # the version of the snap
summary: Olam English Malayalam Dictionary   # 79 char long summary
description: Unofficial Olam desktop client for ubuntu # a longer description for the snap
confinement: strict  # use "strict" to enforce system access only via declared interfaces
base: core18
license: GPL-3.0

apps:
  olam:
    command: bin/desktop-launch olam
    plugs:
     - unity7
     - desktop
     - desktop-legacy
     - wayland
     - home
     - x11
     - network
     - network-bind
     - opengl
    environment:
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
    olam:
        source: .
        #source: https://github.com/tachyons/olam.git
        plugin: qmake
        qt-version: qt5
        build-packages:
          - qt5-default
          - qttools5-dev
          - build-essential
          - qttools5-dev-tools
        stage-packages:
          - libqt5core5a
          - libqt5gui5
          - libqt5widgets5
          - libqt5dbus5
          - libqt5svg5
          - libreadline7
          - libcanberra-gtk-module
          - liblua5.2-0
          - ttf-ubuntu-font-family
          - fonts-dejavu
          - libqt5sql5
          - libqt5sql5-sqlite
          - libatk-adaptor 
          - libgail-common
        after: [desktop-qt5]
    desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
    qt5-gtk-platform:
      plugin: nil
      stage-packages:
        - qt5-gtk-platformtheme
