name: QT CI

on: [push, pull_request]
env:
    QT_VERSION: '5.14.2'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{env.QT_VERSION}}
      - name: Build
        run: |
          qmake "CONFIG +=test"
          make
          make check

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{env.QT_VERSION}}
      - name: Test
        run: |
          qmake "CONFIG +=test"
          make
          make check
      - name: Build
        run: |
          make clean
          qmake 
          make
          make check   
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app.zip
          path: |
            build/release/olam.app
            build/release

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{env.QT_VERSION}}
      - name: Build
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake "CONFIG +=test"
          nmake
          nmake check
        shell: cmd
